/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    messages: Message;
    categories: Category;
    products: Product;
    'office-interior-decor': OfficeInteriorDecor;
    'office-greenery': OfficeGreenery;
    'office-workspace-accessories': OfficeWorkspaceAccessory;
    'office-electronics': OfficeElectronic;
    media: Media;
    orders: Order;
    reviews: Review;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'office-interior-decor': OfficeInteriorDecorSelect<false> | OfficeInteriorDecorSelect<true>;
    'office-greenery': OfficeGreenerySelect<false> | OfficeGreenerySelect<true>;
    'office-workspace-accessories': OfficeWorkspaceAccessoriesSelect<false> | OfficeWorkspaceAccessoriesSelect<true>;
    'office-electronics': OfficeElectronicsSelect<false> | OfficeElectronicsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'manager' | 'user';
  fullName?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  phone: string;
  email: string;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  type: 'category' | 'subcategory' | 'vibe';
  description: string;
  'page-description': string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  category?: string | null;
  name: string;
  slug?: string | null;
  images: (number | Media)[];
  price: number;
  /**
   * Select one subcategories
   */
  subcategory: string;
  /**
   * Select one or more subcategories
   */
  vibe?:
    | (
        | 'minimalist-office-vibe'
        | 'executive-office-vibe'
        | 'modern-professional-office-vibe'
        | 'creative-studio-office-vibe'
        | 'nature-inspired-office-vibe'
      )[]
    | null;
  stock: number;
  delivery: {
    deliveryTime: string;
    pickupAvailable?: boolean | null;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  description: {
    productInformation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    dimensions?: string | null;
    structuralMaterial?: string | null;
    color?: string | null;
    careInstructions?: string | null;
  };
  /**
   * All reviews for this product
   */
  reviews?: (number | Review)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title: string;
  /**
   * Select the product this review belongs to
   */
  product:
    | {
        relationTo: 'office-interior-decor';
        value: number | OfficeInteriorDecor;
      }
    | {
        relationTo: 'office-greenery';
        value: number | OfficeGreenery;
      }
    | {
        relationTo: 'office-workspace-accessories';
        value: number | OfficeWorkspaceAccessory;
      }
    | {
        relationTo: 'office-electronics';
        value: number | OfficeElectronic;
      };
  /**
   * Rating out of 5 stars
   */
  rating: number;
  authorName: string;
  authorEmail: string;
  reviewText: string;
  /**
   * Check to approve this review before displaying
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-interior-decor".
 */
export interface OfficeInteriorDecor {
  id: number;
  category?: string | null;
  name: string;
  slug?: string | null;
  images: (number | Media)[];
  price: number;
  /**
   * Select one subcategories
   */
  subcategory:
    | 'office-desk-shelf-decor'
    | 'office-ambient-lighting-decorative-lights'
    | 'office-wall-decor-accessories'
    | 'office-personalized-statement-decor';
  /**
   * Select one or more subcategories
   */
  vibe?:
    | (
        | 'minimalist-office-vibe'
        | 'executive-office-vibe'
        | 'modern-professional-office-vibe'
        | 'creative-studio-office-vibe'
        | 'nature-inspired-office-vibe'
      )[]
    | null;
  stock: number;
  delivery: {
    deliveryTime: string;
    pickupAvailable?: boolean | null;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  description: {
    productInformation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    dimensions?: string | null;
    structuralMaterial?: string | null;
    color?: string | null;
    careInstructions?: string | null;
  };
  /**
   * All reviews for this product
   */
  reviews?: (number | Review)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-greenery".
 */
export interface OfficeGreenery {
  id: number;
  category?: string | null;
  name: string;
  slug?: string | null;
  images: (number | Media)[];
  price: number;
  /**
   * Select one subcategories
   */
  subcategory: 'office-desk-greenery' | 'office-statement-greenery' | 'greenery-sets-styled-combos';
  /**
   * Select one or more subcategories
   */
  vibe?:
    | (
        | 'minimalist-office-vibe'
        | 'executive-office-vibe'
        | 'modern-professional-office-vibe'
        | 'creative-studio-office-vibe'
        | 'nature-inspired-office-vibe'
      )[]
    | null;
  stock: number;
  delivery: {
    deliveryTime: string;
    pickupAvailable?: boolean | null;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  description: {
    productInformation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    dimensions?: string | null;
    structuralMaterial?: string | null;
    color?: string | null;
    careInstructions?: string | null;
  };
  /**
   * All reviews for this product
   */
  reviews?: (number | Review)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-workspace-accessories".
 */
export interface OfficeWorkspaceAccessory {
  id: number;
  category?: string | null;
  name: string;
  slug?: string | null;
  images: (number | Media)[];
  price: number;
  /**
   * Select one subcategories
   */
  subcategory:
    | 'office-ergonomic-comfort-accessories'
    | 'office-desk-essentials-utility-tools'
    | 'office-productivity-writing-tools'
    | 'office-desk-organizer-storage';
  /**
   * Select one or more subcategories
   */
  vibe?:
    | (
        | 'minimalist-office-vibe'
        | 'executive-office-vibe'
        | 'modern-professional-office-vibe'
        | 'creative-studio-office-vibe'
        | 'nature-inspired-office-vibe'
      )[]
    | null;
  stock: number;
  delivery: {
    deliveryTime: string;
    pickupAvailable?: boolean | null;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  description: {
    productInformation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    dimensions?: string | null;
    structuralMaterial?: string | null;
    color?: string | null;
    careInstructions?: string | null;
  };
  /**
   * All reviews for this product
   */
  reviews?: (number | Review)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-electronics".
 */
export interface OfficeElectronic {
  id: number;
  category?: string | null;
  name: string;
  slug?: string | null;
  images: (number | Media)[];
  price: number;
  /**
   * Select one subcategories
   */
  subcategory: 'office-charging-power-accessories' | 'office-computer-accessories' | 'office-cable-management-tech';
  /**
   * Select one or more subcategories
   */
  vibe?:
    | (
        | 'minimalist-office-vibe'
        | 'executive-office-vibe'
        | 'modern-professional-office-vibe'
        | 'creative-studio-office-vibe'
        | 'nature-inspired-office-vibe'
      )[]
    | null;
  stock: number;
  delivery: {
    deliveryTime: string;
    pickupAvailable?: boolean | null;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  description: {
    productInformation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    dimensions?: string | null;
    structuralMaterial?: string | null;
    color?: string | null;
    careInstructions?: string | null;
  };
  /**
   * All reviews for this product
   */
  reviews?: (number | Review)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  DeliveryDate: string;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymentStatus: 'unpaid' | 'paid' | 'failed' | 'refunded';
  paymentMethod?: ('mpesa' | 'airtel' | 'card' | 'bank' | 'cod') | null;
  transactionId?: string | null;
  customer: {
    name: string;
    email: string;
    phone: string;
  };
  deliveryAddress: {
    city: string;
    areaStreet: string;
    building?: string | null;
    officeNumber?: string | null;
    landmark?: string | null;
    AdditionalDeliveryInformation?: string | null;
  };
  items: {
    product:
      | {
          relationTo: 'office-interior-decor';
          value: number | OfficeInteriorDecor;
        }
      | {
          relationTo: 'office-greenery';
          value: number | OfficeGreenery;
        }
      | {
          relationTo: 'office-workspace-accessories';
          value: number | OfficeWorkspaceAccessory;
        }
      | {
          relationTo: 'office-electronics';
          value: number | OfficeElectronic;
        };
    name: string;
    price: number;
    quantity: number;
    subtotal: number;
    id?: string | null;
  }[];
  AdditionalOrderInformation?: string | null;
  subtotal: number;
  shipping?: number | null;
  total: number;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug?: string | null;
  featuredImage: number | Media;
  category:
    | 'office-setup'
    | 'office-styling'
    | 'productivity'
    | 'buying-guides'
    | 'startup-corporate-solutions'
    | 'workspace-tech-tools';
  author?: string | null;
  publishedDate: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featured?: boolean | null;
  /**
   * Example: 5 minutes
   */
  readTime?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Comma separated keywords
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'office-interior-decor';
        value: number | OfficeInteriorDecor;
      } | null)
    | ({
        relationTo: 'office-greenery';
        value: number | OfficeGreenery;
      } | null)
    | ({
        relationTo: 'office-workspace-accessories';
        value: number | OfficeWorkspaceAccessory;
      } | null)
    | ({
        relationTo: 'office-electronics';
        value: number | OfficeElectronic;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  'page-description'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  images?: T;
  price?: T;
  subcategory?: T;
  vibe?: T;
  stock?: T;
  delivery?:
    | T
    | {
        deliveryTime?: T;
        pickupAvailable?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?:
    | T
    | {
        productInformation?: T;
        dimensions?: T;
        structuralMaterial?: T;
        color?: T;
        careInstructions?: T;
      };
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-interior-decor_select".
 */
export interface OfficeInteriorDecorSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  images?: T;
  price?: T;
  subcategory?: T;
  vibe?: T;
  stock?: T;
  delivery?:
    | T
    | {
        deliveryTime?: T;
        pickupAvailable?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?:
    | T
    | {
        productInformation?: T;
        dimensions?: T;
        structuralMaterial?: T;
        color?: T;
        careInstructions?: T;
      };
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-greenery_select".
 */
export interface OfficeGreenerySelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  images?: T;
  price?: T;
  subcategory?: T;
  vibe?: T;
  stock?: T;
  delivery?:
    | T
    | {
        deliveryTime?: T;
        pickupAvailable?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?:
    | T
    | {
        productInformation?: T;
        dimensions?: T;
        structuralMaterial?: T;
        color?: T;
        careInstructions?: T;
      };
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-workspace-accessories_select".
 */
export interface OfficeWorkspaceAccessoriesSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  images?: T;
  price?: T;
  subcategory?: T;
  vibe?: T;
  stock?: T;
  delivery?:
    | T
    | {
        deliveryTime?: T;
        pickupAvailable?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?:
    | T
    | {
        productInformation?: T;
        dimensions?: T;
        structuralMaterial?: T;
        color?: T;
        careInstructions?: T;
      };
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-electronics_select".
 */
export interface OfficeElectronicsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  images?: T;
  price?: T;
  subcategory?: T;
  vibe?: T;
  stock?: T;
  delivery?:
    | T
    | {
        deliveryTime?: T;
        pickupAvailable?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?:
    | T
    | {
        productInformation?: T;
        dimensions?: T;
        structuralMaterial?: T;
        color?: T;
        careInstructions?: T;
      };
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  DeliveryDate?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  transactionId?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  deliveryAddress?:
    | T
    | {
        city?: T;
        areaStreet?: T;
        building?: T;
        officeNumber?: T;
        landmark?: T;
        AdditionalDeliveryInformation?: T;
      };
  items?:
    | T
    | {
        product?: T;
        name?: T;
        price?: T;
        quantity?: T;
        subtotal?: T;
        id?: T;
      };
  AdditionalOrderInformation?: T;
  subtotal?: T;
  shipping?: T;
  total?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  rating?: T;
  authorName?: T;
  authorEmail?: T;
  reviewText?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  excerpt?: T;
  content?: T;
  featured?: T;
  readTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}